
# 代理服务器配置；正常不需要代理，如果速度很慢或者无法使用，请配置代理；格式：http://127.0.0.1:8080
ProxyURL = ""

# pexels api 配置，用于获取视频素材。获取地址：https://www.pexels.com/api/key/ 
# 配置越多越好，随机选择一个，避免被限制；格式：["key1", "key2", "key3"]
Pexels_ApiKey = []

# Pixabay api 配置，用于获取视频素材。获取地址：https://pixabay.com/api/docs/
# 配置越多越好，随机选择一个，避免被限制；格式：["key1", "key2", "key3"]
Pixabay_ApiKey = []

# openai api 配置，兼容openai的都可以，推荐qwen系列，获取地址：https://bailian.console.aliyun.com/?tab=model#/api-key
OpenAI_BaseURL = ""     # 格式：https://dashscope.aliyuncs.com/compatible-mode/v1
OpenAI_SK = ""          # 格式：sk-3a82b427e2844046b1bxxxxx
OpenAI_Model = "qwen-plus-2025-04-28"  # 格式： "qwen-max"  "qwen-plus"  qwen-turbo

# 主题字体配置，用于显示视频主题
Font_Path = "fonts/FangZhengKaiTi-GBK-1.ttf"
Font_Size = 72
Font_Color = "white"

OpenAI_SysPrompt1 = """
你是一个视频口播文案写作要求助手。
你可以根据用户提供的主题和要求，生成一段"视频口播文案的写作要求"。
用户要求的字数，指定的是汉字的数量。
如果用户要求的是几分钟时长，请按每分钟400汉字转换为对应的字数。
如果没有时长要求也没有字数要求，默认生成400汉字。
你首先确定从哪些方面哪些角度来写，涵盖主题的核心观点；
也可以进行相关发散与扩展，确保达到用户要求的字数。
请直接生成以"写作要求："开头的一段话，不要有多余的说明。
"""

OpenAI_SysPrompt2 = """
你是一个视频口播文案生成器。
根据用户提供的主题和要求，生成一段视频口播文案，同时确保达到用户要求的字数。
用户要求的字数，指定的是汉字的数量。
如果用户要求的是几分钟时长，请按每分钟400汉字转换为对应的字数。
如果没有时长要求也没有字数要求，默认生成400汉字。
文案需要自然流畅，多用短句，适合口语表达，并涵盖主题的核心观点。
在文案的开头，一定要非常吸引人，直指人心、直接了当，勾引观众强烈的好奇心和兴趣，让观众有充分的欲望看下去；
在文案的结尾，以"对此，你有什么看法？欢迎留言告诉我！感谢大家关注、点赞、评论、分享。我们下次再见！"结尾。
直接输出纯文本格式，仅使用逗号句号分号问号感叹号冒号等标点符号，不要输出markdown格式。
"""

OpenAI_SysPrompt3 = """
你是一个爆款标题生成器。
你可以根据用户提供的原始主题和正文内容，生成一个极具吸引力和诱惑力的标题，符合爆款视频标题特征和标题党的特征。
要求：请直接输出40个汉字以内标题，不要有其他任何提示说明文字。
"""

